kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: "kindest/node:v1.30.3"
    labels:
      ingress-ready: "true"
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: /Users/cmoullia/.config/containers/auth.json
    extraPortMappings:
    - containerPort: 443
      hostPort: 8443
      protocol: TCP

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gitea.cnoe.localtest.me:8443"]
      endpoint = ["https://gitea.cnoe.localtest.me"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."gitea.cnoe.localtest.me".tls]
      insecure_skip_verify = true